apiVersion: apps/v1
kind: Deployment

metadata:
  name: autohealops-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: autohealops-backend

  template:
    metadata:
      labels:
        app: autohealops-backend

    spec:
      containers:
        - name: autohealops-backend
          image: vikasgowda12/autohealops-backend:latest

          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15