apiVersion: v1
kind: Service

metadata:
  name: autohealops-service

spec:
  selector:
    app: autohealops-backend

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

  type: LoadBalancer