apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: autohealops-monitor
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: autohealops-backend

  endpoints:
    - port: http
      path: /metrics
      interval: 15s